### ISSUE TITLE
Cannot start with "ModuleNotFoundError" after installing with "pip install esbonio[lsp]"

### ISSUE THREAD

**Issue by yaegassy** [swyddfa/esbonio#147]
## Reproduction Procedure (prepare)

```
mkdir -p /tmp/esbonio-check
cd /tmp/esbonio-check
python3 -m venv venv
source venv/bin/activate
pip install -U esbonio[lsp]
```

## Error

```
(venv) esbonio-check$ python3 -m esbonio --help
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/private/tmp/esbonio-check/venv/lib/python3.9/site-packages/esbonio/__main__.py", line 5, in <module>
    import esbonio.lsp as lsp
  File "/private/tmp/esbonio-check/venv/lib/python3.9/site-packages/esbonio/lsp/__init__.py", line 10, in <module>
    from pygls.features import COMPLETION, INITIALIZE, INITIALIZED, TEXT_DOCUMENT_DID_SAVE
ModuleNotFoundError: No module named 'pygls.features'
```

## It looks like "pygls" is "0.10.2"

```
(venv) esbonio-check$ pip freeze | grep pygls
pygls==0.10.2
```

Looking at this issue, it looks like 0.10.x is not yet supported. https://github.com/swyddfa/esbonio/issues/144

You may need to adjust the package dependencies.

## Misc

As a workaround, I set the pygls version to 0.9.x as shown below, and it started.

```
pip install -U esbonio[lsp] pygls==0.9.1
```

**Comment by alcarney** [comment]
Thank you for such a detailed issue report!

I'm about to merge #148 which should result in esbonio v0.5.1 being released with this issue resolved. Feel free to re-open this issue if the problem persists.

**Comment by leosh64** [comment]
A similar issue still persists with latest version of `esbonio`, this time the module `attrs` can't be found:
```
$ pip freeze | grep esbonio
esbonio==0.16.1
```
Python:
```
$ python --version
Python 3.10.6
```
Error:
```
$ python -m esbonio
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/.local/lib/python3.10/site-packages/esbonio/__main__.py", line 4, in <module>
    from esbonio import cli
  File "/home/user/.local/lib/python3.10/site-packages/esbonio/cli/__init__.py", line 7, in <module>
    from pygls.protocol import default_converter
  File "/home/user/.local/lib/python3.10/site-packages/pygls/protocol.py", line 32, in <module>
    import attrs
ModuleNotFoundError: No module named 'attrs'
```
But `attrs` is installed:
```
$ pip freeze | grep attrs
attrs==21.2.0
cattrs==22.2.0
```
The version of `pygls` is:
```
$ pip freeze | grep pygls
pygls==1.0.1
```

**Comment by alcarney** [comment]
It looks like `import attrs` was only introduced in [`21.3.0`](https://www.attrs.org/en/stable/changelog.html#id7) (originally only `import attr` was available).
Upgrading your installation of `attrs` to at least that version should resolve the issue.

**Comment by leosh64** [comment]
That fixes it, thanks!
