### ISSUE TITLE
"--exclude" option causes an error

### ISSUE THREAD

**Issue by yaegassy** [swyddfa/esbonio#313]
## Description

Hi, @alcarney 

Is the `--exclude` option in esbonio `v0.9.0` working correctly?

### [OK] --include option

```
(venv) check-esbonio$ python3 -m esbonio --include sys
Unable to load module 'sys', missing 'esbonio_setup' function
...snip
```

### [NG] --exclude option

```
(venv) check-esbonio$ python3 -m esbonio --exclude sys
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/yaegassy/sandbox/check-esbonio/venv/lib/python3.10/site-packages/esbonio/__main__.py", line 8, in <module>
    sys.exit(main(cli))
  File "/Users/yaegassy/sandbox/check-esbonio/venv/lib/python3.10/site-packages/esbonio/cli.py", line 72, in main
    modules.remove(mod)
ValueError: list.remove(x): x not in list
```

**Comment by alcarney** [comment]
Ah, looks like there is a bug! 

Internally, the language server is “assembled” by looping through a list of python [modules](https://github.com/swyddfa/esbonio/blob/b5d69ec73a4789bd0168e3a7199952b85d98942e/lib/esbonio/esbonio/lsp/sphinx/__init__.py#L51) and calling any functions called `esbonio_setup`  that are found. The `—include` and `—exclude` options are there to allow users to add and remove modules from this list.

Looks like the server isn’t correctly handling the case where `—exclude` is given a module that is not in the list of defined modules.
