### ISSUE TITLE
Error: command 'esbonio.server.configuration' already exists

### ISSUE THREAD

**Issue by beutlich** [swyddfa/esbonio#339]
After updating to restructuredtext 1.179.0 I observe an error `command 'esbonio.server.configuration' already exists` preventing to preview the sphinx generated documentation.

Log is:

```
The HTML pages are in Docs\PRJ\_build\html.
[Log - 07:19:31] Build complete {"config":{"sphinx":{"version":"2.1.2","confDir":"C:\\Users\\USER\\source\\repos\\Repo\\Docs\\PRJ\\source","srcDir":"C:\\Users\\USER\\source\\repos\\Repo\\Docs\\PRJ\\source","buildDir":"C:\\Users\\USER\\source\\repos\\Repo\\Docs\\PRJ\\_build\\html","builderName":"html"},"server":{"log_level":"error","log_filter":[],"hide_sphinx_output":false}},"error":false,"warnings":0}
Cancel notification for unknown message id "2"
Ignoring notification for unknown method "$/setTraceNotification"
Server shutting down. No more requests!
Server shutting down. No more requests!
Server shutting down. No more requests!
[Log - 07:19:32] Server start command: c:\Users\USER\source\repos\Repo\.venv\Scripts\python.exe -m esbonio
[Log - 07:19:32] LanguageClientOptions: {"documentSelector":[{"scheme":"file","language":"restructuredtext"},{"scheme":"file","language":"python"}],"initializationOptions":{"sphinx":{"srcDir":null,"confDir":"c:\\Users\\USER\\source\\repos\\Repo\\Docs\\PRJ\\source","buildDir":"${workspaceFolder}/Docs/PRJ/_build"},"server":{"logLevel":"error","logFilter":[],"hideSphinxOutput":false}},"outputChannel":{"name":"Esbonio Language Server"}}
[Log - 07:19:32] Starting Language Server
[Log - 07:19:32] Server start command: c:\Users\USER\source\repos\Repo\.venv\Scripts\python.exe -m esbonio
[Log - 07:19:32] LanguageClientOptions: {"documentSelector":[{"scheme":"file","language":"restructuredtext"},{"scheme":"file","language":"python"}],"initializationOptions":{"sphinx":{"srcDir":null,"confDir":"c:\\Users\\USER\\source\\repos\\Repo\\Docs\\PRJ\\source","buildDir":"${workspaceFolder}/Docs/PRJ/_build"},"server":{"logLevel":"error","logFilter":[],"hideSphinxOutput":false}},"outputChannel":{"name":"Esbonio Language Server"}}
[Log - 07:19:32] Starting Language Server
[Log - 07:19:33] Error: Language client is not ready yet
[Error - 07:19:33] Server initialization failed.
Error: command 'esbonio.server.configuration' already exists
	at f.registerCommand (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:28706)
	at Object.registerCommand (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:30813)
	at ExecuteCommandFeature.register (c:\Users\USER\.vscode\extensions\lextudio.restructuredtext-179.0.0\node_modules\vscode-languageclient\lib\client.js:1650:53)
	at ExecuteCommandFeature.initialize (c:\Users\USER\.vscode\extensions\lextudio.restructuredtext-179.0.0\node_modules\vscode-languageclient\lib\client.js:1630:14)
	at LanguageClient.initializeFeatures (c:\Users\USER\.vscode\extensions\lextudio.restructuredtext-179.0.0\node_modules\vscode-languageclient\lib\client.js:2462:21)
	at c:\Users\USER\.vscode\extensions\lextudio.restructuredtext-179.0.0\node_modules\vscode-languageclient\lib\client.js:2147:18
[Log - 07:19:33] Error: command 'esbonio.server.configuration' already exists
[Error - 07:19:33] Starting client failed
Error: command 'esbonio.server.configuration' already exists
	at f.registerCommand (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:28706)
	at Object.registerCommand (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:30813)
	at ExecuteCommandFeature.register (c:\Users\USER\.vscode\extensions\lextudio.restructuredtext-179.0.0\node_modules\vscode-languageclient\lib\client.js:1650:53)
	at ExecuteCommandFeature.initialize (c:\Users\USER\.vscode\extensions\lextudio.restructuredtext-179.0.0\node_modules\vscode-languageclient\lib\client.js:1630:14)
	at LanguageClient.initializeFeatures (c:\Users\USER\.vscode\extensions\lextudio.restructuredtext-179.0.0\node_modules\vscode-languageclient\lib\client.js:2462:21)
	at c:\Users\USER\.vscode\extensions\lextudio.restructuredtext-179.0.0\node_modules\vscode-languageclient\lib\client.js:2147:18
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 125 source files that are out of date
updating environment:
building [mo]: targets for 0 po files that are out of date
125 added, 0 changed, 0 removed
reading sources... [  0%] index
building [html]: targets for 125 source files that are out of date
updating environment:
125 added, 0 changed, 0 removed
```

VS Code is:

```
Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

settings.json is:

```json
{
    "python.linting.pylintEnabled": true,
    "python.linting.enabled": true,
    "python.linting.pycodestyleEnabled": false,
    "python.testing.unittestEnabled": false,
    "python.testing.nosetestsEnabled": false,
    "python.testing.pytestEnabled": true,
    "python.testing.cwd": "${workspaceFolder}",
    "python.defaultInterpreterPath": "${workspaceFolder}/.venv/Scripts",
    "[restructuredtext]": {
        "editor.wordWrap": "wordWrapColumn",
        "editor.wordWrapColumn": 80,
        "editor.rulers": [80],
    },
    "rewrap.wrappingColumn": 80,
    "restructuredtext.confPath": "${workspaceFolder}/Docs/PRJ/source",
    "restructuredtext.linter.run": "off",
    "restructuredtext.sphinxBuildPath": "${workspaceFolder}/.venv/Scripts/sphinx-build",
    "restructuredtext.builtDocumentationPath": "${workspaceFolder}/Docs/PRJ/_build",
    "restructuredtext.preview.scrollEditorWithPreview": false,
    "restructuredtext.preview.scrollPreviewWithEditor": false,
    "restructuredtext.updateDelay": 1000,
    "restructuredtext.linter.disabled": true,
    "restructuredtext.linter.disabledLinters": ["rstcheck", "doc8", "rst-lint"],
    "esbonio.server.enabled": true,
    "esbonio.sphinx.buildDir": "${workspaceFolder}/Docs/PRJ/_build",
    "esbonio.sphinx.confDir": "${workspaceFolder}/Docs/PRJ/source",
}

```

I also notice, that `"esbonio.sphinx.confDir"` is changed to an absolute path while `"esbonio.sphinx.buildDir"` is not touched.

**Comment by alcarney** [comment]
Interesting.... the `command 'esbonio.server.configuration' already exists` is something I see fairly often when working on the server and assumed it was caused from server crashes not cleaning up after themselves....

```
Server shutting down. No more requests!
Server shutting down. No more requests!
Server shutting down. No more requests!
[Log - 07:19:32] Server start command: c:\Users\USER\source\repos\Repo\.venv\Scripts\python.exe -m esbonio
[Log - 07:19:32] LanguageClientOptions: {"documentSelector":[{"scheme":"file","language":"restructuredtext"},{"scheme":"file","language":"python"}],"initializationOptions":{"sphinx":{"srcDir":null,"confDir":"c:\\Users\\USER\\source\\repos\\Repo\\Docs\\PRJ\\source","buildDir":"${workspaceFolder}/Docs/PRJ/_build"},"server":{"logLevel":"error","logFilter":[],"hideSphinxOutput":false}},"outputChannel":{"name":"Esbonio Language Server"}}
[Log - 07:19:32] Starting Language Server
[Log - 07:19:32] Server start command: c:\Users\USER\source\repos\Repo\.venv\Scripts\python.exe -m esbonio
[Log - 07:19:32] LanguageClientOptions: {"documentSelector":[{"scheme":"file","language":"restructuredtext"},{"scheme":"file","language":"python"}],"initializationOptions":{"sphinx":{"srcDir":null,"confDir":"c:\\Users\\USER\\source\\repos\\Repo\\Docs\\PRJ\\source","buildDir":"${workspaceFolder}/Docs/PRJ/_build"},"server":{"logLevel":"error","logFilter":[],"hideSphinxOutput":false}},"outputChannel":{"name":"Esbonio Language Server"}}
[Log - 07:19:32] Starting Language Server
```
This part seems interesting... do you know why the server was shutting down - had you asked it to restart or anything?

@lextm It looks like the server is being restarted twice, any ideas why that might be? I'm assuming the fact two instances are starting at once they are both trying to register the same command.

**Comment by lextm** [comment]
@beutlich Your settings file include too many obsolete settings (vscode-restructuredtext prompts you to remove them). Please remove them and try again.

> "esbonio.sphinx.confDir" is changed to an absolute path while "esbonio.sphinx.buildDir" is not touched

This is expected. Currently no easy way to modify "esbonio.sphinx.buildDir".

**Comment by beutlich** [comment]
This settings.json is part of a git repository to serve a larger developer community. As we never know which (VS Code or ) restructuredtext version is used at the developers's site, we decided to keep both the legacy and the newer settings in the expectation that inappropriate settings will be ignored.

**Comment by lextm** [comment]
@beutlich If you leave the obsolete settings, their values are still being copied over to overwrite whatever you assign to the new settings (release 179.0.0 and above).

**Comment by beutlich** [comment]
Which I see as some kind of issue as settings.json gets modified.

**Comment by lextm** [comment]
We might close this one here, and focus on https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/368

I will write more details there.

**Comment by beutlich** [comment]
https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/368 seems like a duplicate.

**Comment by alcarney** [comment]
Closing as this appears to now be resolved in the vscode-restructuredtext repo

**Comment by beutlich** [comment]
> Closing as this appears to now be resolved in the vscode-restructuredtext repo

Nice, which version is it?

**Comment by alcarney** [comment]
Looks like the fix landed in v182 
https://github.com/vscode-restructuredtext/vscode-restructuredtext/releases/tag/182.0.0
