### ISSUE TITLE
Esbonio fails on pygls 1.0.0, works on pygls 0.13.1

### ISSUE THREAD

**Issue by davbeek** [swyddfa/esbonio#512]
Using pygls 1.0.0 cause Esbonio to fail, pygls 0.13.1 works. Version 1.0.0 appears to miss several modules that are available in 0.13.1.

> Error: Command failed: /Users/dvbeek/opt/miniconda3/bin/python -m esbonio --version
Traceback (most recent call last):
  File "/Users/dvbeek/opt/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/dvbeek/opt/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/dvbeek/opt/miniconda3/lib/python3.9/site-packages/esbonio/__main__.py", line 5, in <module>
    from esbonio.lsp.sphinx import DEFAULT_MODULES
  File "/Users/dvbeek/opt/miniconda3/lib/python3.9/site-packages/esbonio/lsp/__init__.py", line 14, in <module>
    from pygls.lsp.methods import CODE_ACTION
ModuleNotFoundError: No module named 'pygls.lsp.methods'

**Comment by alcarney** [comment]
That's expected as #484 has not landed yet.

Unfortunately while I [pinned](https://github.com/swyddfa/esbonio/blob/d8c6dac6d5f3b58abfc88e2a90b7230a7c50faab/lib/esbonio/setup.cfg#L39) the version of pygls for the PyPI package I forgot to do the same for the [conda package](https://github.com/conda-forge/esbonio-feedstock/blob/0c4fd060e9c1fa3dc4f516a179c4e14afb8b5890/recipe/meta.yaml#L26)! :man_facepalming: 

I should be able to get a fixed definition out soon!

**Comment by alcarney** [comment]
Hopefully an updated version of the package will be available soon, let me know if there's still an issue
