### ISSUE TITLE
[Bug]: AttributeError: 'InitializationOptions' object has no attribute 'sphinx'

### ISSUE THREAD

**Issue by nandgator** [swyddfa/esbonio#545]
```py
Failed to handle user defined notification "initialize": (InitializeParams(capabilities=ClientCapabilities(workspace=WorkspaceClientCapabilities(apply_edit=True, workspace_edit=WorkspaceEditClientCapabilities(document_changes=True, resource_operations=[<ResourceOperationKind.Create: 'create'>, <ResourceOperationKind.Rename: 'rename'>, <ResourceOperationKind.Delete: 'delete'>], failure_handling=<FailureHandlingKind.TextOnlyTransactional: 'textOnlyTransactional'>, normalizes_line_endings=True, change_annotation_support=WorkspaceEditClientCapabilitiesChangeAnnotationSupportType(groups_on_label=True)), did_change_configuration=DidChangeConfigurationClientCapabilities(dynamic_registration=True), did_change_watched_files=DidChangeWatchedFilesClientCapabilities(dynamic_registration=True, relative_pattern_support=True), symbol=WorkspaceSymbolClientCapabilities(dynamic_registration=True, symbol_kind=WorkspaceSymbolClientCapabilitiesSymbolKindType(value_set=[<SymbolKind.File: 1>, <SymbolKind.Module: 2>, <SymbolKind.Namespace: 3>, <SymbolKind.Package: 4>, <SymbolKind.Class: 5>, <SymbolKind.Method: 6>, <SymbolKind.Property: 7>, <SymbolKind.Field: 8>, <SymbolKind.Constructor: 9>, <SymbolKind.Enum: 10>, <SymbolKind.Interface: 11>, <SymbolKind.Function: 12>, <SymbolKind.Variable: 13>, <SymbolKind.Constant: 14>, <SymbolKind.String: 15>, <SymbolKind.Number: 16>, <SymbolKind.Boolean: 17>, <SymbolKind.Array: 18>, <SymbolKind.Object: 19>, <SymbolKind.Key: 20>, <SymbolKind.Null: 21>, <SymbolKind.EnumMember: 22>, <SymbolKind.Struct: 23>, <SymbolKind.Event: 24>, <SymbolKind.Operator: 25>, <SymbolKind.TypeParameter: 26>]), tag_support=WorkspaceSymbolClientCapabilitiesTagSupportType(value_set=[<SymbolTag.Deprecated: 1>]), resolve_support=WorkspaceSymbolClientCapabilitiesResolveSupportType(properties=['location.range'])), execute_command=ExecuteCommandClientCapabilities(dynamic_registration=True), workspace_folders=True, configuration=True, semantic_tokens=SemanticTokensWorkspaceClientCapabilities(refresh_support=True), code_lens=CodeLensWorkspaceClientCapabilities(refresh_support=True), file_operations=FileOperationClientCapabilities(dynamic_registration=True, did_create=True, will_create=True, did_rename=True, will_rename=True, did_delete=True, will_delete=True), inline_value=InlineValueWorkspaceClientCapabilities(refresh_support=True), inlay_hint=InlayHintWorkspaceClientCapabilities(refresh_support=True), diagnostics=DiagnosticWorkspaceClientCapabilities(refresh_support=True)), text_document=TextDocumentClientCapabilities(synchronization=TextDocumentSyncClientCapabilities(dynamic_registration=True, will_save=True, will_save_wait_until=True, did_save=True), completion=CompletionClientCapabilities(dynamic_registration=True, completion_item=CompletionClientCapabilitiesCompletionItemType(snippet_support=True, commit_characters_support=True, documentation_format=[<MarkupKind.Markdown: 'markdown'>, <MarkupKind.PlainText: 'plaintext'>], deprecated_support=True, preselect_support=True, tag_support=CompletionClientCapabilitiesCompletionItemTypeTagSupportType(value_set=[<CompletionItemTag.Deprecated: 1>]), insert_replace_support=True, resolve_support=CompletionClientCapabilitiesCompletionItemTypeResolveSupportType(properties=['documentation', 'detail', 'additionalTextEdits']), insert_text_mode_support=CompletionClientCapabilitiesCompletionItemTypeInsertTextModeSupportType(value_set=[<InsertTextMode.AsIs: 1>, <InsertTextMode.AdjustIndentation: 2>]), label_details_support=True), completion_item_kind=CompletionClientCapabilitiesCompletionItemKindType(value_set=[<CompletionItemKind.Text: 1>, <CompletionItemKind.Method: 2>, <CompletionItemKind.Function: 3>, <CompletionItemKind.Constructor: 4>, <CompletionItemKind.Field: 5>, <CompletionItemKind.Variable: 6>, <CompletionItemKind.Class: 7>, <CompletionItemKind.Interface: 8>, <CompletionItemKind.Module: 9>, <CompletionItemKind.Property: 10>, <CompletionItemKind.Unit: 11>, <CompletionItemKind.Value: 12>, <CompletionItemKind.Enum: 13>, <CompletionItemKind.Keyword: 14>, <CompletionItemKind.Snippet: 15>, <CompletionItemKind.Color: 16>, <CompletionItemKind.File: 17>, <CompletionItemKind.Reference: 18>, <CompletionItemKind.Folder: 19>, <CompletionItemKind.EnumMember: 20>, <CompletionItemKind.Constant: 21>, <CompletionItemKind.Struct: 22>, <CompletionItemKind.Event: 23>, <CompletionItemKind.Operator: 24>, <CompletionItemKind.TypeParameter: 25>]), insert_text_mode=<InsertTextMode.AdjustIndentation: 2>, context_support=True, completion_list=CompletionClientCapabilitiesCompletionListType(item_defaults=['commitCharacters', 'editRange', 'insertTextFormat', 'insertTextMode'])), hover=HoverClientCapabilities(dynamic_registration=True, content_format=[<MarkupKind.Markdown: 'markdown'>, <MarkupKind.PlainText: 'plaintext'>]), signature_help=SignatureHelpClientCapabilities(dynamic_registration=True, signature_information=SignatureHelpClientCapabilitiesSignatureInformationType(documentation_format=[<MarkupKind.Markdown: 'markdown'>, <MarkupKind.PlainText: 'plaintext'>], parameter_information=SignatureHelpClientCapabilitiesSignatureInformationTypeParameterInformationType(label_offset_support=True), active_parameter_support=True), context_support=True), declaration=DeclarationClientCapabilities(dynamic_registration=True, link_support=True), definition=DefinitionClientCapabilities(dynamic_registration=True, link_support=True), type_definition=TypeDefinitionClientCapabilities(dynamic_registration=True, link_support=True), implementation=ImplementationClientCapabilities(dynamic_registration=True, link_support=True), references=ReferenceClientCapabilities(dynamic_registration=True), document_highlight=DocumentHighlightClientCapabilities(dynamic_registration=True), document_symbol=DocumentSymbolClientCapabilities(dynamic_registration=True, symbol_kind=DocumentSymbolClientCapabilitiesSymbolKindType(value_set=[<SymbolKind.File: 1>, <SymbolKind.Module: 2>, <SymbolKind.Namespace: 3>, <SymbolKind.Package: 4>, <SymbolKind.Class: 5>, <SymbolKind.Method: 6>, <SymbolKind.Property: 7>, <SymbolKind.Field: 8>, <SymbolKind.Constructor: 9>, <SymbolKind.Enum: 10>, <SymbolKind.Interface: 11>, <SymbolKind.Function: 12>, <SymbolKind.Variable: 13>, <SymbolKind.Constant: 14>, <SymbolKind.String: 15>, <SymbolKind.Number: 16>, <SymbolKind.Boolean: 17>, <SymbolKind.Array: 18>, <SymbolKind.Object: 19>, <SymbolKind.Key: 20>, <SymbolKind.Null: 21>, <SymbolKind.EnumMember: 22>, <SymbolKind.Struct: 23>, <SymbolKind.Event: 24>, <SymbolKind.Operator: 25>, <SymbolKind.TypeParameter: 26>]), hierarchical_document_symbol_support=True, tag_support=DocumentSymbolClientCapabilitiesTagSupportType(value_set=[<SymbolTag.Deprecated: 1>]), label_support=True), code_action=CodeActionClientCapabilities(dynamic_registration=True, code_action_literal_support=CodeActionClientCapabilitiesCodeActionLiteralSupportType(code_action_kind=CodeActionClientCapabilitiesCodeActionLiteralSupportTypeCodeActionKindType(value_set=['', 'quickfix', 'refactor', 'refactor.extract', 'refactor.inline', 'refactor.rewrite', 'source', 'source.organizeImports'])), is_preferred_support=True, disabled_support=True, data_support=True, resolve_support=CodeActionClientCapabilitiesResolveSupportType(properties=['edit']), honors_change_annotations=False), code_lens=CodeLensClientCapabilities(dynamic_registration=True), document_link=DocumentLinkClientCapabilities(dynamic_registration=True, tooltip_support=True), color_provider=DocumentColorClientCapabilities(dynamic_registration=True), formatting=DocumentFormattingClientCapabilities(dynamic_registration=True), range_formatting=DocumentRangeFormattingClientCapabilities(dynamic_registration=True), on_type_formatting=DocumentOnTypeFormattingClientCapabilities(dynamic_registration=True), rename=RenameClientCapabilities(dynamic_registration=True, prepare_support=True, prepare_support_default_behavior=<PrepareSupportDefaultBehavior.Identifier: 1>, honors_change_annotations=True), folding_range=FoldingRangeClientCapabilities(dynamic_registration=True, range_limit=5000, line_folding_only=True, folding_range_kind=FoldingRangeClientCapabilitiesFoldingRangeKindType(value_set=['comment', 'imports', 'region']), folding_range=FoldingRangeClientCapabilitiesFoldingRangeType(collapsed_text=False)), selection_range=SelectionRangeClientCapabilities(dynamic_registration=True), publish_diagnostics=PublishDiagnosticsClientCapabilities(related_information=True, tag_support=PublishDiagnosticsClientCapabilitiesTagSupportType(value_set=[<DiagnosticTag.Unnecessary: 1>, <DiagnosticTag.Deprecated: 2>]), version_support=False, code_description_support=True, data_support=True), call_hierarchy=CallHierarchyClientCapabilities(dynamic_registration=True), semantic_tokens=SemanticTokensClientCapabilities(requests=SemanticTokensClientCapabilitiesRequestsType(range=True, full=SemanticTokensClientCapabilitiesRequestsTypeFullType1(delta=True)), token_types=['namespace', 'type', 'class', 'enum', 'interface', 'struct', 'typeParameter', 'parameter', 'variable', 'property', 'enumMember', 'event', 'function', 'method', 'macro', 'keyword', 'modifier', 'comment', 'string', 'number', 'regexp', 'operator', 'decorator'], token_modifiers=['declaration', 'definition', 'readonly', 'static', 'deprecated', 'abstract', 'async', 'modification', 'documentation', 'defaultLibrary'], formats=[<TokenFormat.Relative: 'relative'>], dynamic_registration=True, overlapping_token_support=False, multiline_token_support=False, server_cancel_support=True, augments_syntax_tokens=True), linked_editing_range=LinkedEditingRangeClientCapabilities(dynamic_registration=True), moniker=None, type_hierarchy=TypeHierarchyClientCapabilities(dynamic_registration=True), inline_value=InlineValueClientCapabilities(dynamic_registration=True), inlay_hint=InlayHintClientCapabilities(dynamic_registration=True, resolve_support=InlayHintClientCapabilitiesResolveSupportType(properties=['tooltip', 'textEdits', 'label.tooltip', 'label.location', 'label.command'])), diagnostic=DiagnosticClientCapabilities(dynamic_registration=True, related_document_support=False)), notebook_document=NotebookDocumentClientCapabilities(synchronization=NotebookDocumentSyncClientCapabilities(dynamic_registration=True, execution_summary_support=True)), window=WindowClientCapabilities(work_done_progress=True, show_message=ShowMessageRequestClientCapabilities(message_action_item=ShowMessageRequestClientCapabilitiesMessageActionItemType(additional_properties_support=True)), show_document=ShowDocumentClientCapabilities(support=True)), general=GeneralClientCapabilities(stale_request_support=GeneralClientCapabilitiesStaleRequestSupportType(cancel=True, retry_on_content_modified=['textDocument/semanticTokens/full', 'textDocument/semanticTokens/range', 'textDocument/semanticTokens/full/delta']), regular_expressions=RegularExpressionsClientCapabilities(engine='ECMAScript', version='ES2020'), markdown=MarkdownClientCapabilities(parser='marked', version='1.1.0', allowed_tags=None), position_encodings=['utf-16']), experimental=None), process_id=298833, client_info=InitializeParamsClientInfoType(name='Visual Studio Code', version='1.75.1'), locale='en-gb', root_path='/home/user-name/PROJECT_PATH', root_uri='file:///home/user-name/PROJECT_PATH', initialization_options={'sphinx': {'buildDir': '/home/user-name/.config/Code/User/workspaceStorage/326b2b701ec4b16b0d8eb59057b7ef23/swyddfa.esbonio/sphinx', 'builderName': 'html', 'confDir': None, 'configOverrides': {}, 'doctreeDir': None, 'forceFullBuild': False, 'keepGoing': False, 'makeMode': True, 'numJobs': 1, 'quiet': False, 'silent': False, 'srcDir': None, 'tags': [], 'verbosity': 0, 'warningIsError': False}, 'server': {'logLevel': 'error', 'logFilter': [], 'hideSphinxOutput': False, 'showDeprecationWarnings': False, 'completion': {'preferredInsertBehavior': 'replace'}}}, trace='off', work_done_token=None, workspace_folders=[WorkspaceFolder(uri='file:///home/user-name/PROJECT_PATH', name='pyvalidators')]),)
  + Exception Group Traceback (most recent call last):
  |   File "/home/user-name/.cache/pypoetry/virtualenvs/validators-lKxACWzr-py3.9/lib/python3.9/site-packages/pygls/protocol.py", line 87, in decorator
  |     self._execute_notification(user_func, *args, **kwargs)
  |   File "/home/user-name/.cache/pypoetry/virtualenvs/validators-lKxACWzr-py3.9/lib/python3.9/site-packages/pygls/protocol.py", line 231, in _execute_notification
  |     handler(*params)
  |   File "/home/user-name/.cache/pypoetry/virtualenvs/validators-lKxACWzr-py3.9/lib/python3.9/site-packages/esbonio/lsp/__init__.py", line 112, in on_initialize
  |     ls.initialize(params)
  |   File "/home/user-name/.cache/pypoetry/virtualenvs/validators-lKxACWzr-py3.9/lib/python3.9/site-packages/esbonio/lsp/sphinx/__init__.py", line 138, in initialize
  |     super().initialize(params)
  |   File "/home/user-name/.cache/pypoetry/virtualenvs/validators-lKxACWzr-py3.9/lib/python3.9/site-packages/esbonio/lsp/rst/__init__.py", line 437, in initialize
  |     self.user_config = converter.structure(
  |   File "/home/user-name/.cache/pypoetry/virtualenvs/validators-lKxACWzr-py3.9/lib/python3.9/site-packages/cattrs/converters.py", line 309, in structure
  |     return self._structure_func.dispatch(cl)(obj, cl)
  |   File "<cattrs generated structure esbonio.lsp.rst.config.InitializationOptions>", line 10, in structure_InitializationOptions
  |     if errors: raise __c_cve('While structuring ' + 'InitializationOptions', errors, __cl)
  | cattrs.errors.ClassValidationError: While structuring InitializationOptions (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "<cattrs generated structure esbonio.lsp.rst.config.InitializationOptions>", line 6, in structure_InitializationOptions
    |     res['server'] = __c_structure_server(o['server'], __c_type_server)
    |   File "<cattrs generated structure esbonio.lsp.rst.config.ServerConfig>", line 40, in structure_ServerConfig
    |     if errors: raise __c_cve('While structuring ' + 'ServerConfig', errors, __cl)
    | cattrs.errors.ClassValidationError: While structuring ServerConfig (1 sub-exception)
    | Structuring class InitializationOptions @ attribute server
    +-+---------------- 1 ----------------
      | Exception Group Traceback (most recent call last):
      |   File "<cattrs generated structure esbonio.lsp.rst.config.ServerConfig>", line 6, in structure_ServerConfig
      |     res['completion'] = __c_structure_completion(o['completion'], __c_type_completion)
      |   File "<cattrs generated structure esbonio.lsp.rst.config.ServerCompletionConfig>", line 10, in structure_ServerCompletionConfig
      |     if errors: raise __c_cve('While structuring ' + 'ServerCompletionConfig', errors, __cl)
      | cattrs.errors.ClassValidationError: While structuring ServerCompletionConfig (1 sub-exception)
      | Structuring class ServerConfig @ attribute completion
      +-+---------------- 1 ----------------
        | Traceback (most recent call last):
        |   File "<cattrs generated structure esbonio.lsp.rst.config.ServerCompletionConfig>", line 6, in structure_ServerCompletionConfig
        |     res['preferred_insert_behavior'] = __c_structure_preferred_insert_behavior(o['preferredInsertBehavior'], __c_type_preferred_insert_behavior)
        |   File "/home/user-name/.cache/pypoetry/virtualenvs/validators-lKxACWzr-py3.9/lib/python3.9/site-packages/cattrs/converters.py", line 377, in _structure_error
        |     raise StructureHandlerNotFoundError(msg, type_=cl)
        | cattrs.errors.StructureHandlerNotFoundError: Unsupported type: typing.Literal['insert', 'replace']. Register a structure hook for it.
        | Structuring class ServerCompletionConfig @ attribute preferred_insert_behavior
        +------------------------------------
Failed to handle user defined notification "initialized": (InitializedParams(),)
Traceback (most recent call last):
  File "/home/user-name/.cache/pypoetry/virtualenvs/validators-lKxACWzr-py3.9/lib/python3.9/site-packages/esbonio/lsp/sphinx/__init__.py", line 150, in _initialize_sphinx
    return self.create_sphinx_app(self.user_config)  # type: ignore
  File "/home/user-name/.cache/pypoetry/virtualenvs/validators-lKxACWzr-py3.9/lib/python3.9/site-packages/esbonio/lsp/sphinx/__init__.py", line 317, in create_sphinx_app
    sphinx = options.sphinx
AttributeError: 'InitializationOptions' object has no attribute 'sphinx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user-name/.cache/pypoetry/virtualenvs/validators-lKxACWzr-py3.9/lib/python3.9/site-packages/pygls/protocol.py", line 87, in decorator
    self._execute_notification(user_func, *args, **kwargs)
  File "/home/user-name/.cache/pypoetry/virtualenvs/validators-lKxACWzr-py3.9/lib/python3.9/site-packages/pygls/protocol.py", line 231, in _execute_notification
    handler(*params)
  File "/home/user-name/.cache/pypoetry/virtualenvs/validators-lKxACWzr-py3.9/lib/python3.9/site-packages/esbonio/lsp/__init__.py", line 119, in on_initialized
    ls.initialized(params)
  File "/home/user-name/.cache/pypoetry/virtualenvs/validators-lKxACWzr-py3.9/lib/python3.9/site-packages/esbonio/lsp/sphinx/__init__.py", line 144, in initialized
    self.app = self._initialize_sphinx()
  File "/home/user-name/.cache/pypoetry/virtualenvs/validators-lKxACWzr-py3.9/lib/python3.9/site-packages/esbonio/lsp/sphinx/__init__.py", line 172, in _initialize_sphinx
    {"config": self.configuration, "error": True, "warnings": 0},
  File "/home/user-name/.cache/pypoetry/virtualenvs/validators-lKxACWzr-py3.9/lib/python3.9/site-packages/esbonio/lsp/sphinx/__init__.py", line 123, in configuration
    sphinx_config.silent = self.user_config.sphinx.silent  # type: ignore
AttributeError: 'InitializationOptions' object has no attribute 'sphinx'
```

What went wrong?

---

Extension: `v0.10.6`
VSCode: `v1.75.1`
Python `v3.9.0`
Esbonio: `0.16.1`

**Comment by alcarney** [comment]
> What went wrong?

The main error is buried in the middle of the stack trace... 
`cattrs.errors.StructureHandlerNotFoundError: Unsupported type: typing.Literal['insert', 'replace']. Register a structure hook for it.`

It looks like `cattrs` [does not support](https://catt.rs/en/stable/history.html#id37) `Literals` out of the box on Python 3.9.0. 
Upgrading your Python to `v3.9.1` or later should fix it, though it it should also be possible to add an explicit hook for this type in the next release of `esbonio`

**Comment by alcarney** [comment]
> What went wrong?

The main error is buried in the middle of the stack trace... 
`cattrs.errors.StructureHandlerNotFoundError: Unsupported type: typing.Literal['insert', 'replace']. Register a structure hook for it.`

It looks like `cattrs` [does not support](https://catt.rs/en/stable/history.html#id37) `Literals` out of the box on Python 3.9.0. 
Upgrading your Python to `v3.9.1` or later should fix it, though it it should also be possible to add an explicit hook for this type in the next release of `esbonio`

**Comment by nandgator** [comment]
Upgrading to `v3.9.1` works. Shall I close this issue?

**Comment by alcarney** [comment]
Sure, if you feel it's resolved 🙂
